# The azure pipeline template for PR build, Official build, and upgrade version build

parameters:
- name: 'jobFilters'
  type: object
  default: ''
- name: 'preSteps'
  type: stepList
  default: []
- name: 'buildSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []
- name: jobGroups
  type: object
  default: []
- name: jobVariables
  type: object
  default: []
jobs:
- template: azure-pipelines-job-groups.yml
  parameters:
    jobFilters: ${{ parameters.jobFilters }}
    jobVariables: ${{ parameters.jobVariables }}
    preSteps:
      - template: cleanup.yml
      - ${{ parameters.preSteps }}
      - bash: |
          set -ex
          # cpu info
          uname -a
          cat /proc/cpuinfo
          # meminfo
          free -m
          # disk
          df -h
        condition: always()
        displayName: "Display system configuration 1#"
      - script: |
          if [ -n "$(CACHE_MODE)" ] && echo $(PLATFORM_AZP) | grep -E -q "^(vs|broadcom|mellanox)$"; then
            CACHE_OPTIONS="SONIC_DPKG_CACHE_METHOD=$(CACHE_MODE) SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/$(PLATFORM_AZP)"
            BUILD_OPTIONS="$(BUILD_OPTIONS) $CACHE_OPTIONS"
            echo "##vso[task.setvariable variable=BUILD_OPTIONS]$BUILD_OPTIONS"
          fi
        displayName: "Set cache options"
      - checkout: self
        submodules: recursive
        condition: eq(variables.SKIP_CHECKOUT, '') 
        displayName: 'Checkout code'
      - script: |
          BRANCH_NAME=$(Build.SourceBranchName)
          [ -n "$SYSTEM_PULLREQUEST_PULLREQUESTID" ] && BRANCH_NAME="$SYSTEM_PULLREQUEST_TARGETBRANCH-$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
          git checkout -b $BRANCH_NAME
          sudo modprobe overlay
          sudo apt-get install -y acl
          sudo bash -c "echo 1 > /proc/sys/vm/compact_memory"
          sudo apt install -y python3-pip
          sudo pip3 install j2cli
          ENABLE_DOCKER_BASE_PULL=y make PLATFORM=$(PLATFORM_AZP) PLATFORM_ARCH=$(PLATFORM_ARCH) $(BUILD_OPTIONS) configure
        displayName: 'Make configure'
      - bash: |
          set -ex
          free -m
          df -h
        condition: always()
        displayName: "Display system configuration 2#"
    postSteps:
      - bash: |
          set -ex
          free -m
          df -h
        condition: always()
        displayName: "Display system configuration 3#"
      - script: cp target -r $(Build.ArtifactStagingDirectory)/
        displayName: Copy Artifacts
        condition: always()
      - publish:  $(Build.ArtifactStagingDirectory)
        artifact: 'sonic-buildimage.$(GROUP_NAME)$(GROUP_EXTNAME)'
        displayName: "Archive sonic image"
      - publish:  $(Build.ArtifactStagingDirectory)
        condition: failed()
        artifact: 'sonic-buildimage.$(GROUP_NAME)$(GROUP_EXTNAME)$(System.JobAttempt)'
        displayName: "Archive failed sonic image"
      - ${{ parameters.postSteps }}
      - template: cleanup.yml
      - bash: |
          set -ex
          free -m
          df -h
        condition: always()
        displayName: "Display system configuration end#"
    jobGroups: ${{ parameters.jobGroups }}
    buildSteps: ${{ parameters.buildSteps }}
